name: website_snapshot

on:
  pull_request:
  push:
    branches-ignore:
      - "master"
    paths:
      - ".github/workflows/website.yml"
      - "docs/**"
      - "website/**"

jobs:
  publish_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          cd website
          npm install
          npm run build
